/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controladores.ControladorBus;
import controladores.ControladorRuta;
import controladores.ControladorUsuario;
import excepciones.CampoVacioException;
import excepciones.ContraseñaNoCoincideException;
import excepciones.PersonaYaRegistradaException;
import excepciones.UsuarioYaRegistradoException;
import javax.swing.JOptionPane;
import modelos.Administrador;
import modelos.Cajero;
import modelos.Despachador;
import modelos.Pasajero;
import modelos.Usuario;

/**
 *
 * @author SANTIAGO
 */
public class VentanaLogIn extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogIn
     */
    controladores.ControladorBus controladorBus;
    controladores.ControladorRuta controladorRuta;
    ControladorUsuario controladorUsuario;

    public VentanaLogIn() {
        initComponents();
        setLocationRelativeTo(this);
        controladorUsuario = new ControladorUsuario();
        controladorBus = new ControladorBus();
        controladorRuta = new ControladorRuta();
//        try {
//            Administrador admin = new Administrador(0, "san", "123", "Santiago", "Bernal", "321", "Masculino");
//            Pasajero pasajero = new Pasajero("bernal", "123", "Santiago", "Bernal", "123", "Masculino");
//            Cajero cajero = new Cajero(0, "cajero", "123", "cajero", "caje", "1234", "Masculino");
//            Despachador despachador = new Despachador(0, "despachador", "123", "despacha", "dor", "0000", "Masculino");
//            controladorUsuario.registrarUsuario(admin);
//            controladorUsuario.registrarUsuario(pasajero);
//            controladorUsuario.registrarUsuario(cajero);
//            controladorUsuario.registrarUsuario(despachador);
//            
//        } catch (UsuarioYaRegistradoException | PersonaYaRegistradaException ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }

        txtContraseña.setEchoChar((char) 0);
    }


    public static Usuario usuarioLogeado;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        txtCorreoLogIn = new javax.swing.JTextField();
        btnIngresarLogIn = new javax.swing.JButton();
        btnRegistrarLogIn = new javax.swing.JButton();
        iconoCandado = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnIconoOjoAbierto = new javax.swing.JButton();
        btnIconoOjoCerrado = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log in", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jPanel1.add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtCorreoLogIn.setText("Usuario-Correo");
        txtCorreoLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoLogInMouseClicked(evt);
            }
        });
        jPanel1.add(txtCorreoLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 45, 159, -1));

        btnIngresarLogIn.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresarLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar.png"))); // NOI18N
        btnIngresarLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 30));

        btnRegistrarLogIn.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRegistrar.png"))); // NOI18N
        btnRegistrarLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, 30));

        iconoCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        jPanel1.add(iconoCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtContraseña.setText("Contraseña");
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 100, 130, -1));

        btnIconoOjoAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo abierto.png"))); // NOI18N
        btnIconoOjoAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconoOjoAbiertoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIconoOjoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 20, -1));

        btnIconoOjoCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo cerrado.png"))); // NOI18N
        btnIconoOjoCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconoOjoCerradoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIconoOjoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, 190));

        jButton2.setText("Cerrar programa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Transportes SA.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLogInActionPerformed
        // TODO add your handling code here:
        try {
            if (txtCorreoLogIn.getText().isEmpty() || txtCorreoLogIn.getText().equals("Usuario-Correo")
                    || txtContraseña.getText().isEmpty() || txtContraseña.getText().equals("Contraseña")) {
                throw new CampoVacioException();
            }
            Usuario resul = controladorUsuario.buscarUsuario(txtCorreoLogIn.getText());
            if (resul instanceof Administrador && resul != null) {
                if (txtContraseña.getText().equals(resul.getContraseña())) {
                    usuarioLogeado = resul;
                    this.dispose();
                    ventanas.VentanaAdministrador ventana = new VentanaAdministrador(this);
                    ventana.setVisible(true);
                    limpiarCampos();
                } else {
                    throw new ContraseñaNoCoincideException();
                }
            } else if (resul instanceof Pasajero && resul != null) {
                if (txtContraseña.getText().equals(resul.getContraseña())) {
                    usuarioLogeado = resul;
                    VentanaPasajero ventana = new VentanaPasajero(this);
                    ventana.setVisible(true);
                    this.dispose();
                    limpiarCampos();
                } else {
                    throw new ContraseñaNoCoincideException();
                }
            } else if (resul instanceof Despachador && resul != null) {
                if (txtContraseña.getText().equals(resul.getContraseña())) {
                    usuarioLogeado = resul;
                    this.dispose();
                    ventanas.VentanaDespachador ventana = new VentanaDespachador(this);
                    ventana.setVisible(true);
                    limpiarCampos();
                } else {
                    throw new ContraseñaNoCoincideException();
                }
            } else if (resul instanceof Cajero && resul != null) {
                if (txtContraseña.getText().equals(resul.getContraseña())) {
                    usuarioLogeado = resul;
                    VentanaCajero ventana = new VentanaCajero(this);
                    ventana.setVisible(true);
                    this.dispose();
                    limpiarCampos();
                }

            } else {
                JOptionPane.showMessageDialog(null, "No se encontro persona con este correo o usuario");
            }

        } catch (CampoVacioException | ContraseñaNoCoincideException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnIngresarLogInActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "Estas seguro de que deseas cerrar la aplicacion?");
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegistrarLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLogInActionPerformed
        // TODO add your handling code here:
        VentanaRegistro ventana = new VentanaRegistro(this);
        ventana.setVisible(true);
        this.dispose();
        limpiarCampos();
    }//GEN-LAST:event_btnRegistrarLogInActionPerformed

    private void btnIconoOjoAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoOjoAbiertoActionPerformed
        // TODO add your handling code here:
        btnIconoOjoAbierto.setVisible(false);
        txtContraseña.setEchoChar((char) 0);
        btnIconoOjoCerrado.setVisible(true);
    }//GEN-LAST:event_btnIconoOjoAbiertoActionPerformed

    private void btnIconoOjoCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoOjoCerradoActionPerformed
        // TODO add your handling code here:
        btnIconoOjoCerrado.setVisible(false);
        txtContraseña.setEchoChar('*');
        btnIconoOjoAbierto.setVisible(true);
    }//GEN-LAST:event_btnIconoOjoCerradoActionPerformed

    private void txtCorreoLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoLogInMouseClicked
        // TODO add your handling code here:
        txtCorreoLogIn.setText(null);
    }//GEN-LAST:event_txtCorreoLogInMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        txtContraseña.setText(null);
        txtContraseña.setEchoChar('*');
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void limpiarCampos() {
        txtCorreoLogIn.setText("Usuario-Correo");
        txtContraseña.setText("Contraseña");
        txtContraseña.setEchoChar((char) 0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconoOjoAbierto;
    private javax.swing.JButton btnIconoOjoCerrado;
    private javax.swing.JButton btnIngresarLogIn;
    private javax.swing.JButton btnRegistrarLogIn;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoCandado;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreoLogIn;
    // End of variables declaration//GEN-END:variables
}
